version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: new_world_lab3
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
