name: QAWorkflow

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: 1.21

      - name: Build
        uses: ./.github/actions/build
        with:
          target-directory: './'

      - name: Tests
        uses: ./.github/actions/tests
  
  lint:
    # https://primegopher.medium.com/configure-the-golangci-lint-workflow-for-your-golang-applications-6e765f2146c5
    # https://golangci-lint.run/
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.0
          args: --timeout 3m 
